name: shell comnands

on: [push]
# on: 
#  schedule: 
#     - cron: '*/1 * * * *'

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: print the string
        run: echo "Welcome to Deploy Cloud!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python comand
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest
    steps: 
      - name: Directory Powreshell
        run: Get-Location
      
      - name: Directory Bash
        run: |
          pwd
          echo "Successfully, executed the Bash commands"
        shell: bash
